spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blackops
    username: blackops
    password: blackOps
  cache:
    type: redis
  redis:
    port: 6379
    password: password
    host: localhost

corta:
  default:
    expiration_time_in_days: 7
    short_url_length: 8
    redirection_url: https://www.google.com